### PR TITLE
Update ruby 3.0.4

### PR DESCRIPTION
**Pull request by vickyprahastra**

### CODE REVIEW

**Comment by haffla** [comment]
Hello @vickyprahastra,

I do agree that it's time to update the development Ruby version but why exactly 3.0.4 and not 3.1.x for example?

**Comment by vickyprahastra** [comment]
> Hello @vickyprahastra,
> 
> I do agree that it's time to update the development Ruby version but why exactly 3.0.4 and not the latest stable 3.1.x for example?

Yes, i think we can go 3.1.x and do test, currently i upgrade my rails app to ruby 3.0.4.

**Comment by haffla** [comment]
Any update on this?

**Comment by saviokmua** [comment]
Any update on this?

**Pull request closed without merging**
