### PR TITLE
Add support for Ruby 3

### PR DESCRIPTION
**Pull request by mrhaddad**

### CODE REVIEW

**Comment by ollizeyen** [comment]
Can we get this to rubygems soon? @stephanieminn can you do the releases now?

**Comment by ollizeyen** [comment]
@mrhaddad Looks like https://github.com/madeintandem/jsonb_accessor/blob/master/.travis.yml needs some adjustment to go green. bundler gem version and ruby version doesn't fit.

**Comment by haffla** [comment]
This does not make it compatible with Ruby 3. Have a look my fork of this repo if you're looking for Ruby 3 support (with all tests green on Travis): https://github.com/haffla/jsonb_accessor

Anyway it seems that this software has been abandoned by the creators. Discussion here: https://github.com/madeintandem/jsonb_accessor/pull/128

**Comment by haffla** [comment]
Closing this in favor of https://github.com/madeintandem/jsonb_accessor/pull/132

**Pull request closed without merging**
