### PR TITLE
Allow using store_key or aliased key

### LINKED ISSUE #80: Can't update/assign model with json value from params
Here is my model:

```ruby
class Listing < ApplicationRecord
    jsonb_accessor :weekend_price, weekend_price_enabled: [:boolean, store_key: :enabled, default: false],
                                   weekend_price_value: [:integer, store_key: :value]

end
```

When I tried to update model from params:

```ruby

listing.update(weekend_price: { enabled: true })
```

Then I got an error: 

```
ActiveModel::MissingAttributeError: can't write unknown attribute `enabled`
```

I'm using `1.0.0.beta.6` version.

### PR DESCRIPTION
**Pull request by joelvh**
Closes #80

### CODE REVIEW

**Comment by joelvh** [comment]
ah @haffla just saw you fixed it already!

**Comment by joelvh** [comment]
@haffla your changes are a bit broader, so maybe take a look here to see if there's anything additional in my PR to consider. Otherwise, feel free to close!

Thanks for fixing this!

**Comment by haffla** [comment]
Ah damn @joelvh. Really sorry. I thought you had seen my [comment](https://github.com/madeintandem/jsonb_accessor/issues/80#issuecomment-840026490). Thank you anyway for your contribution. My changes have been a bit broader 'cause I did some refactoring + added some comments. I think it's easier to grasp what's going on now.

**Comment by joelvh** [comment]
No problem! Thanks for fixing.

**Pull request closed without merging**
